### ISSUE TITLE
Passing a struct that implements `gen` instead of a ItemGenerator

### ISSUE THREAD

**Issue by GTimothy** [WorldSEnder/yew-virtualized#2]
I haven't used your library yet but I am interested,  as I would like to populate a large list in a project of mine.

Am I understanding right that right now VirtualList expects a [`ItemGenerator`](https://github.com/WorldSEnder/yew-virtualized/blob/master/src/lib.rs#L29) struct as input?

As ItemGenerator is quite a simple Struct, could it be more flexible for ItemGenerator to be a Trait instead of a struct, so that one could pass as arbitrarily complex a Struct so long as it implements [`ItemGenerator::gen`](https://github.com/WorldSEnder/yew-virtualized/blob/master/src/lib.rs#L30)?

**Comment by WorldSEnder** [comment]
I'm not sure I fully understand the proposal, there are two interpretations:

1. Make `VirtualList` generic over an underlying `G: ItemGenerator` where `ItemGenerator` would be a new trait. This sounds reasonable, but would probably also lead to more codegen in the long run for marginally better performance (basically using `G` directly in the component instead of erasing through an indirection). Feel free to prove me wrong on this point.

2. You simply want the trait to replace the call to `ItemGenerator::gen` for more ergonomics. Consider instead that you could just implement `From<YourGen> for ItemGenerator` for your structs (the impl would probably call [`VirtualList::item_gen`](https://docs.rs/yew-virtualized/latest/yew_virtualized/struct.VirtualList.html#method.item_gen) under the hood) and pass it as `items={your_gen.into()}` instead of `items={VirtualList::item_gen(|idx| your_gen.gen(idx))}`

By offering only an abstract way of constructing an ItemGenerator, I'm trying to keep the implementation maximally flexible until I can decide on "the best" interface I want to have there. So far, the current one works fine though, at least for me.

Hope that helps. Note that I kinda need to update the library to yew 0.20 at some point anyway. Feel free to send a PR my way if you end up patching it yourself ^^

**Comment by GTimothy** [comment]
I was thinking **1.**:

I'll try to be a little more specific and rephrase:
Say I have a set of structures D, like a `Vec<D>`. These D implement `Into<Html>`. I don't need to render these D structures until I scroll to them.

So, maybe my knowledge is lacking here, but how do write a function `Fn(usize) -> Html` that can get the proper D struct at index `idx` and generate the Html from it? 

Seeing as I did not see how to (without making it FnOnce or something), I thought that what would suffice would be to have a struct `MyGen{vec:Vec<D>}` that would implement 
```rust
 fn emit(&self, idx: usize) -> Html { 
    self.vec[idx].into()
}
```
This could be enforced via a Trait requirement.

> Note that I kinda need to update the library to yew 0.20 at some point anyway. Feel free to send a PR my way if you end up patching it yourself ^^

I have just done that because my project is dependent on 0.20, I'll send a PR (there was only one line to change + the cargo file)

**Comment by WorldSEnder** [comment]
> So, maybe my knowledge is lacking here, but how do write a function `Fn(usize) -> Html` that can get the proper D struct at index `idx` and generate the Html from it?

You need to be prepared to render a specific index multiple times, if the user scrolls back and forth. Something like the following should work

```rust
let vec: Vec<D> = todo!();
let items = VirtualList::item_gen(move |idx| {
    vec[idx].clone().into() // With D: Clone
    (&vec[idx]).into()      // OR With Html: From<&D>
    vec[idx].view()         // OR with some D::view(&self) -> Html method
});
```

I see that currently the API accepts only `impl Fn(usize) -> Html`. It might be possible to widen this to `impl FnMut(usize) -> Html`, anyway.

Thanks for the PR, will review it in the coming days, after I hand in my thesis ^^

**Comment by GTimothy** [comment]
> So, maybe my knowledge is lacking here, but how do write a function `Fn(usize) -> Html` that can get the proper D struct at index idx and generate the Html from it?

> Something like the following should work

Well, I guess my knowledge *was* lacking ! Thanks, your suggestion worked. I was using a borrowed `Rc<Vec<D>>` so I was able to `Rc::clone()` it before using it in 'items'.
